### ISSUE TITLE
Any ETA for this

### ISSUE THREAD

**Issue by K-prog** [YigitEkin/CLIPAway#1]
Hi guys, this is great work, I was going through [abyildirim](https://github.com/abyildirim)'s work on inpainting and found this one for [masked based inpainting](https://github.com/abyildirim/inst-inpaint/issues/13), this seems really promising and wanted to know what would be the size of these models and when can we expect this to come out?

**Comment by YigitEkin** [comment]
Hi, thank you for your interest in our work. We plan on releasing the code and the weights of the model within a week. In terms of the model size, our best performing model is based on [SD-Inpaint Pipeline](https://huggingface.co/runwayml/stable-diffusion-inpainting) which has approximately 1.1B parameters. Our proposed adapter (alpha-clip vision transformer + IP-Adapter + MLP projection block) has approximately 313M parameters which makes the total size approximately 1.4B. We also plan on releasing a gradio demo as well which in our opinion would make playing around with the model easier.
