### ISSUE TITLE
Request for Updated Model Link

### ISSUE THREAD

**Issue by jinchengxuexi** [YigitEkin/CLIPAway#3]
I've encountered a problem while trying to access and use the model [Stable Diffusion Inpainting](https://huggingface.co/runwayml/stable-diffusion-inpainting). The link seems to be broken and I'm unable to access it properly. Is there an updated link or alternative available?

Here's what I've tried:
- Directly accessing the link, but received a 404 error.
- Checked my internet connection, which is fine.

If possible, I would appreciate an updated link or guidance on how to obtain this model. Thank you very much!

Looking forward to your reply!

**Comment by YigitEkin** [comment]
Hi,

RunwayML removed their weights from Hugging Face, but no worries—the same ones are available at [botp/stable-diffusion-v1-5-inpainting](https://huggingface.co/botp/stable-diffusion-v1-5-inpainting) (just the access key changed). I've updated the [inference_config.yaml](https://github.com/YigitEkin/CLIPAway/blob/main/config/inference_config.yaml), but I forgot to update the README—thanks for catching that! Let me know if the replacement proposed below fixes the issue, and thanks for your interest in our work!

```python
# OLD MODEL KEY
model_id = "runwayml/stable-diffusion-inpainting"

# NEW MODEL KEY
model_id = "botp/stable-diffusion-v1-5-inpainting"

sd_pipeline = StableDiffusionInpaintPipeline.from_pretrained(
   model_id,  safety_checker=None, torch_dtype=torch.float32
)
```
